M48
; DRILL file {KiCad 9.0.3} date 2025-08-17T20:12:08+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-17T20:12:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X220.98Y-53.34
X220.98Y-142.24
T2
X66.98Y-53.51
X66.98Y-142.07
M30
